### ISSUE TITLE
Support inline substitutions

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-api#13]
**Background:**

Tools do not always support XML element substitution.  The recommended work-around has been to manually edit the XML schemas to replace element substitution groups with inline elements.  Manually-edited subset schemas will be overwritten the next time the subset has to be regenerated.

**Task:**

- [ ] Add global flag to CMF file to inline all substitution groups
- [ ] Add individual element flag to CMF file to inline specific substitution group
- [ ] Add reference back to original substitution group to inlined substitutions
- [ ] Transform original CMF file to simplified CMF file

**Requirements:**

- [ ] Code feature
- [ ] Test feature
  - [ ] Expected pass
  - [ ] Expected fail with wrong extension
  - [ ] Expected fail with invalid CMF
- [ ] Add Javadoc
- [ ] Add feature to Readme
