### ISSUE TITLE
Support flattened class types

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-api#14]
**Background:**

The type hierarchy in the reference NIEM model can cause issues in tools that build classes for each type. 

**Task:**

- [ ] Add global flag to CMF file to flatten all class types.
- [ ] Add individual class type flag to CMF file to flatten specific type.
- [ ] Add inherited properties directly to a type
  - [ ] Add metadata to flattened types so original type hierarchy is documented.
  - [ ] Recurse on parent type
  - [ ] Remove extension
- [ ] Transform original CMF file to simplified CMF file

**Requirements:**

- [ ] Code feature
- [ ] Test feature
  - [ ] Expected pass
  - [ ] Expected fail
- [ ] Add Javadoc
- [ ] Add feature to Readme
