### ISSUE TITLE
Support flattened literal types

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-api#15]
**Background:**

- The type hierarchy in the reference NIEM model can cause issues in tools that build classes for each type. 
- Literal types can be either complex (carries a value and can contain attributes) or simple (carries a value only).
- Flattening literal types simplifies code sets that have traditionally been defined as complex and simple type pairs.

**Task:**

- [ ] Add global flag to CMF file to flatten all literal types.
- [ ] Add individual literal type flag to CMF file to flatten specific type.
- [ ] Add metadata to flattened types indicating original structure
- [ ] Flatten complex literal types with attributes to a single complex literal type
- [ ] Flatten complex literal types without attributes to a single simple data type
- [ ] Transform original CMF file to simplified CMF file

**Requirements:**

- [ ] Code feature
- [ ] Test feature
  - [ ] Expected pass
  - [ ] Expected fail
- [ ] Add Javadoc
- [ ] Add feature to Readme
