### ISSUE TITLE
Support custom literal constraints on properties

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-api#16]
**Background:**

It is straight-forward in NIEM to add facets such as `maxLength` or `pattern` to simple types to support literal-value constraints.  Each constraint on a type will apply to all properties of that type.

Users may want to have custom constraints on properties of the same type, such as `nc:TextType`.  For example, they may want a last name to have at most 30 characters and a description field to have at most 2,000 characters.  But NIEM only has one `nc:TextType` and it cannot have different sets of constraints.

Schematron supports these kinds of custom property constraints but it is not often written or used for validation.

**Task:**

- [ ] Add facet metadata to CMF literal properties (complex or simple)
- [ ] Create custom types for each affected property 
  - [ ] Flatten type
  - [ ] Add facets 
- [ ] Add metadata to customized properties identifying original type
- [ ] Transform original CMF file to simplified CMF file

**Requirements:**

- [ ] Code feature
- [ ] Test feature
  - [ ] Expected pass
  - [ ] Expected fail
- [ ] Add Javadoc
- [ ] Add feature to Readme
