### ISSUE TITLE
Support custom property types to allow different type profiles

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-api#17]
**Background:**

Cardinality is set in NIEM on reusable types.  For example, `nc:PersonType` may contain property `nc:PersonName`, which could be defined in a subset to occur min=1, max=1 times (required) and `nc:PersonBirthDate`, which could be defined to occur min=0, max=` times (optional).

Each person in the model would then have the same occurrent constraints (required name, optional birth date), because they are all based on the same type `nc:PersonType`.

It can be useful to have custom occurrence constrains for properties based on the same type.  For example, an IEPD may want to have birth date required for a subset but prohibited for a judge.

Schematron supports these kinds of custom property occurrence constraints but it is not often written or used for validation.

**Task:**

- [ ] Create custom types for selected properties
- [ ] Add custom sub-property cardinalities to CMF object properties, including max=0 to omit
  - [ ] Sub-properties come from the flattened type, which includes contained and inherited properties
- [ ] Add metadata to simplified customized properties
- [ ] Add metadata to simplified new types
- [ ] Transform original CMF file to simplified CMF file

**Requirements:**

- [ ] Code feature
- [ ] Test feature
  - [ ] Expected pass
  - [ ] Expected fail
- [ ] Add Javadoc
- [ ] Add feature to Readme
